---
title: "Hw 2 - water dsitricts"
author: "Renee LaManna, Alia Ajina"
date: "4/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(janitor)
library(cowplot)
library(patchwork)
library(ggplot2)
library(ggpubr)
```

```{r}
mac <- read_csv(here("data", "water_districts.csv")) %>% 
  clean_names

```


```{r}
mac_longer <- pivot_longer(data = mac,
                             cols = mc_kern:mc_ventura,
                             names_to = "district",
                             values_to = "mc")
```

```{r}
ggplot(data = mac_longer, aes(x = reduction, y = mc)) +
  geom_point(size = .6, aes(color = district)) +
  theme_minimal() +
  geom_smooth(aes(color = district)) + 
  # stat_regline_equation(label.x=80, label.y=70) 
  labs(y = "Price ($/Acre Foot)", x = "Acre Foot")


  
```


```{r}
# linear models for each district

lm_kern <- lm(mc_kern~0+reduction, data = mac)
lm_mojave <- lm(mc_mojave~0+reduction, data = mac)
lm_antelope <- lm(mc_antelope~0+reduction, data = mac)
lm_ventura <- lm(mc_ventura~0+reduction, data = mac)

lm_kern
lm_mojave 
lm_antelope
lm_ventura
```

``` {r}
# fitting line for kern
mod.kern <- lm(mc_kern ~ 0 + reduction, data = mac)
kern.baseline <- 150
kern_data <- tibble(reduction = 0:150) # create vector of equally spaced numbers
predicted_mc <- predict(mod.kern, newdata = kern_data)
kern_data <- kern_data %>% mutate(predicted_mc = predicted_mc)
# fitting line for mojave
mod.mojave <- lm(mc_mojave ~ 0 + reduction, data = mac)
mojave.baseline <-140
mojave_data <- tibble(reduction = 0:140) # create vector of equally spaced numbers
predicted_mc <- predict(mod.mojave, newdata = mojave_data)
mojave_data <- mojave_data %>% mutate(predicted_mc = predicted_mc)
# fitting line for antelope
mod.antelope <- lm(mc_antelope ~ 0 + reduction, data = mac)
antelope.baseline <- 220
antelope_data <- tibble(reduction = 0:220)
predicted_mc <- predict(mod.antelope, newdata = antelope_data)
antelope_data <- antelope_data %>% mutate(predicted_mc = predicted_mc)
# fitting the line for ventura
mod.ventura <- lm(mc_ventura ~ 0 + reduction, data = mac)
ventura.baseline <-245
ventura_data <- tibble(reduction = 0:245)
predicted_mc <- predict(mod.ventura, newdata = ventura_data)
ventura_data <- ventura_data %>% mutate(predicted_mc=predicted_mc)




# plotting predicted line
ggplot(data = mac_longer, aes(x=reduction, y = mc)) +
  geom_point(aes(color = district), size = .6) +
  geom_line(data = kern_data, aes(x = reduction, y = predicted_mc)) +
  geom_line(data = mojave_data, aes(x = reduction, y = predicted_mc)) +
  geom_line(data = antelope_data, aes(x = reduction, y = predicted_mc)) +
  geom_line(data = ventura_data, aes(x = reduction, y = predicted_mc))
  
```



```{r}
# derive districts demand curve or use as baseline (no policy) - abatement
kern_data_demand <- kern_data %>%  mutate(water_demand = kern.baseline-reduction)
mojave_data_demand <- mojave_data %>%  mutate(water_demand = mojave.baseline-reduction)
antelope_data_demand <- antelope_data %>%  mutate(water_demand = antelope.baseline-reduction)
ventura_data_demand <- ventura_data %>%  mutate(water_demand = ventura.baseline-reduction)

# Using demand data for kern and mojave, join them into on dataset for plotting

joined_demand <- bind_rows("Mojave" = mojave_data_demand,
                           "Kern" = kern_data_demand, 
                           "Antelope" = antelope_data_demand,
                           "Ventura" = ventura_data_demand, .id = "District")

# plot the demand

ggplot(joined_demand, aes(x=water_demand,y = predicted_mc, color = District)) +
  geom_line(size=1) +
  labs(x = "Water Demand (AF)", y = "$/AF") +
  theme_minimal() +
  scale_color_manual(values = c("sienna", "darkseagreen", "goldenrod", "steelblue"))  +
  annotate("text", x = 210, y = 315, label = "MB(water use) = 343.5-2.3x",color = "darkseagreen", size = 3) +
  annotate("text", x = 210, y = 270, label = "MB(water use) = 532.6-3.8x",color = "goldenrod", size = 3) +
   annotate("text", x = 210, y = 360, label = "MB(water use) = 628.8-2.9x",color = "sienna", size = 3) +
   annotate("text", x = 210, y = 226, label = "MB(water use) = 435.1-1.8x",color = "steelblue", size = 3)
   
```







